language: node_js
node_js:
    - "stable"
cache:
  directories:
    - "node_modules"
install:
  - yarn
  - yarn add -g codecov
script: >
  ./bin/mocha --opts /dev/null --reporter spec
  tests/spec.js
  #  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  #  - codecov